### ISSUE TITLE
"In Duty" condition set incorrectly

### ISSUE THREAD

**Issue by KuroZantetsuken** [Aida-Enna/GraphicsConfig#2]
The preset for "In Duty" follows the condition ID 91 "BoundToDuty97" instead of ID 34 "BoundByDuty" making it apply when queuing with the Duty Finder and not when inside of a duty. The "In Combat" condition also does not seem to work at all while inside duties, not sure if related. I can make a separate issue for this if needed.

**Comment by Aida-Enna** [comment]
It checks for all 4 of the "BoundForDuty" conditions, but you're right - It looks like 97 (ID: 91) is obsolete and was renamed to "InDutyQueue", so I'll take it out. As for the "In Combat" condition, that's working as intended. The "Duty" selection will override the "In Combat" selection because otherwise it would load a preset for the duty and then overwrite it each time you got into combat and then set it back to "Default" each time you finished the combat in the duty, defeating the purpose of the "Duty" selection.

I can't really think of use case to do otherwise, but if you have any ideas, lemme know.

**Comment by KuroZantetsuken** [comment]
I see! Thank you so much for your work, I have been wanting a plugin like this for years. It would be nice if "In Combat" worked regardless of anything else as that is pretty much the only time I care about maximising FPS, but "In Duty" is already really nice. 

Something else I noticed that might not be intended though is that "Cutscene or Gpose" returns to "Default" after loading into a duty, instead of "In Duty", meaning that if I have set anything for "Default" and "Cutscene or Gpose" then "In Duty" gets ignored, as every duty starts with a cutscene condition. The setup I have for this is: 
- Default: High
- In Duty: Low
- Cutscene or Gpose: High
- Everything else on None.

I would expect this to still put me on Low in a duty, but I end up on High.

Thank you again, if there is anything else I can provide to help I would be more than happy to!

**Comment by Aida-Enna** [comment]
Happy to help! And yeah, if I could track what's going on more reliably I could make it work better, but I think how it is right now is the best I can do without checking every second, which is overkill IMO.

About the cutscene/duty issue though, definitely not intended. I'll add in code to ignore the cutscene check if you're in a duty, good call!
